Feature/videohosting api
youngliqui/videohosting-api pull request #2
Opened 2024-10-13 17:49 UTC by youngliqui

2024-10-21 16:30 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
не надо возвращать 404. 
Нужно просто вернуть пустой список

2024-10-21 16:31 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    public ResponseEntity<Page<UserInfoDTO>> getAllUsers(
ResponseEntity не обязателен - есть аннотация для указания стандартного кода ответа. 
Если есть исключение, то для него пишется отдельный exception handler advice

2024-10-21 16:31 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    public ResponseEntity<User> updateUser(@PathVariable Long userId,
нельзя выставлять entity наружу. Только dto

2024-10-21 16:32 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
никаких Try catch'ей быть не должно, для этого есть exception handler advice

2024-10-21 16:34 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            throw new CustomValidationException(bindingResult.getAllErrors().toString());
Такой проверки и exception'а быть не должно - у тебя должно работать все так, что ты просто ставишь аннотации валидации, если нужна кастомная проверка - пишешь кастомный валидатор. Spring сам вызывает эти валидации и бросает стандартное исключение

2024-10-21 16:34 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    @GetMapping("/{userId}/subscription")
/{userId}/subscription**_s_**

2024-10-21 16:35 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    @PatchMapping(path = "/{userId}")
path не обязательно указывать

2024-10-21 16:36 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    }
/me - неподходящее имя для такого эндпоинта

2024-10-21 16:36 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    }
да и смысла в нем я не вижу

2024-10-21 16:37 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +        this.userSubscriptionService = userSubscriptionService;
руками писать конструктор не нужно, есть Lombok с аннотацией RequiredArgsConstructor

2024-10-21 16:37 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            @PathVariable("userId") Long userId,
дублировать userId не обязательно - по умолчанию берется название параметра метода

2024-10-21 16:39 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/ChannelController.java
> +        }
здесь все аналогично комментам и UserController

2024-10-21 16:44 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/ChannelController.java
> +                                                                @RequestBody JsonPatch patch) {
Какой-то костыль с JsonPatch. Просто пишется одна dto с нужными параметрами для изменения - все, дальше работаешь как тебе надо. А тут ты выставил наружу в контрактах какой-то непонятный JsonPatch, явного контракта для клиента не определил.
Patch обновления легко делаются через mapstruct - там есть такие настройки, как, например, игнорировать null значения

2024-10-21 16:44 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/ChannelController.java
> +            @RequestPart(value = "categoryName", required = false) String categoryName,
зачем это все разделять? Почему просто не сделать все в одном RequestBody?

2024-10-21 16:44 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/controller/ChannelController.java
> +            @RequestPart(value = "categoryName", required = false) String categoryName,
У тебя даже дто под это дело уже есть - ChannelUpdateDTO

2024-10-21 16:46 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/avatar/AvatarServiceImpl.java
> +            throw new AvatarEncodeException("Failed to encode avatar: " + e.getMessage());
это больше похоже не на сервис бизнес-слоя, а на утильный класс. Ты же можешь весь код, который тут написан, применить к любому изображению, не только к аватару

2024-10-21 16:46 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/channel/information/ChannelInformationServiceImpl.java
> +        this.channelMapper = channelMapper;
тоже lombok, так же как и в контроллерах

2024-10-21 16:48 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementService.java
> +    boolean canUserChange(Long channelId, User currentUser);
canUserChange не согласуется с остальными методами этого интерфейса. У тебя должен появиться отдельный класс для проверки таких вещей

2024-10-21 16:50 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/updater/channel/impl/LanguageChannelUpdater.java
> +        }
все эти updater'ы - это лишнее. Весь код по своей сути шаблонный.
Я уже написал в комментах, что для таких апдейтов подойдет mapstruct

2024-10-21 16:52 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/user/subscription/UserSubscriptionService.java
> +    List<UserSubscriptionDTO> getUserSubscriptions(Long userId);
на данном этапе это излишне, можно перенести в UserInformationService.
Такой вариант сейчас только путает

2024-10-21 16:54 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/category/CategoryService.java
> +    Category getCategoryByName(String name);
Написал - хорошо. Но раз уж на то пошло, то на этом месте скорее должен быть запрос по id, а не имени

2024-10-21 17:01 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/updater/channel/impl/LanguageChannelUpdater.java
> +        }
Даже без мапстракта можно придумать что-то поизящнее. Например, через функциональные интерфейсы и хэш мапу прописать маппинг, обработку null'а как-нибудь там вынести и переиспользовать

2024-10-21 17:05 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementService.java
> +    ChannelExtendedInfoDTO applyPatchToChannel(Long channelId, JsonPatch patch) throws JsonPatchException, JsonProcessingException;
Лучше просто patchChannel или вообще как-нибудь уйти от patch.

2024-10-21 17:06 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementServiceImpl.java
> +                .build();
это все мог сделать mapstruct

2024-10-21 17:06 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementServiceImpl.java
> +                new CategoryChannelUpdater(categoryService)
Ты используешь Spring или как?)

2024-10-21 17:11 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/mapper/ChannelMapper.java
> +    @Mapping(target = "categoryName", expression = "java(channel.getCategory().getName())")
вместо expressions лучше использовать такую штуку, как named методы в mapstruct

2024-10-21 17:12 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/mapper/ChannelMapper.java
> +    @Mapping(target = "categoryName", expression = "java(channel.getCategory().getName())")
вместо channel.getCategory().getName() можно использовать точечную нотацию:
category.name

2024-10-21 17:12 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/mapper/ChannelMapper.java
> +        return channel.getSubscribers() != null ? (long) channel.getSubscribers().size() : 0;
optional тут можно

2024-10-21 17:13 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/model/Channel.java
> +    @SequenceGenerator(name = "channelsIdSeqGen", sequenceName = "channels_id_seq", allocationSize = 1)
мне кажется, указывать явно название sequence не обязательно

2024-10-21 17:14 UTC, Akizmostr commented on src/main/java/ru/clevertec/videohosting_api/service/user/management/UserManagementService.java
> +    User applyPatchToUser(Long userId, JsonPatch patch) throws JsonPatchException, JsonProcessingException;
patchUser

2024-10-21 17:15 UTC, Akizmostr requested changes
.

2024-10-23 11:35 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
Убрал проверку. Возвращаю просто пустой список в этом случае

2024-10-23 12:01 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    public ResponseEntity<User> updateUser(@PathVariable Long userId,
Исправил. Теперь возвращаю UserInfoDTO вместо сущности User.

2024-10-23 12:09 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
Убрал try catch из UserController. Добавил обработку этих ошибок в глобальный обработчик ошибок.

2024-10-23 12:13 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    @GetMapping("/{userId}/subscription")
Так и планировал изначально (/{userId}/subscriptions). Исправил

2024-10-23 12:15 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    }
Делал больше для проверки, чтобы правильно доставало текущего пользователя. 
Убрал этот эндпоинт полностью.

2024-10-23 12:22 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +        this.userSubscriptionService = userSubscriptionService;
Согласен. Убрал в классах конструктор и добавил аннотацию @RequiredArgsConstructor

2024-10-23 12:32 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            @PathVariable("userId") Long userId,
Убрал дублирования названий в аннотациях @PathVariable и @RequestPart

2024-10-23 13:36 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/ChannelController.java
> +            @RequestPart(value = "categoryName", required = false) String categoryName,
Была проблема в том, что @RequestBody не работал с form-data форматом. У меня же в ChannelUpdateDTO есть поле MultipartFile avatar. 
Сейчас использовал аннотацию @ModelAttribute и всё заработало.

2024-10-23 13:43 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/user/subscription/UserSubscriptionService.java
> +    List<UserSubscriptionDTO> getUserSubscriptions(Long userId);
Перенес метод getUserSubscriptions в UserInformationService. UserSubscriptionService удалил.

2024-10-23 13:49 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/mapper/ChannelMapper.java
> +        return channel.getSubscribers() != null ? (long) channel.getSubscribers().size() : 0;
Заменил на optional.

2024-10-23 14:13 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/mapper/ChannelMapper.java
> +    @Mapping(target = "categoryName", expression = "java(channel.getCategory().getName())")
Исправил. Использовал вместо expressions @Named методы

2024-10-23 15:05 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementServiceImpl.java
> +                .build();
Не получалось сделать это преобразование. Но сейчас разобрался, исправил.

2024-10-23 18:14 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +    public ResponseEntity<Page<UserInfoDTO>> getAllUsers(
Убрал ResponseEntity и указал аннотации для указания стандартного кода ответа.

2024-10-23 20:44 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementService.java
> +    boolean canUserChange(Long channelId, User currentUser);
Данный метод перенес в класс AccessService

2024-10-23 21:00 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/UserController.java
> +            throw new CustomValidationException(bindingResult.getAllErrors().toString());
Убрал проверки на наличие ошибок валидации. Добавил её в глобальный обработчик ошибок.

2024-10-23 21:12 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/avatar/AvatarServiceImpl.java
> +            throw new AvatarEncodeException("Failed to encode avatar: " + e.getMessage());
Логику перенес в утилитарный класс ImageUtils

2024-10-23 22:55 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/controller/ChannelController.java
> +                                                                @RequestBody JsonPatch patch) {
Увидел такое решение для Patch запросов, захотел попробовать.
Сейчас переделал всё через mapstruct.

2024-10-23 23:01 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/updater/channel/impl/LanguageChannelUpdater.java
> +        }
Убрал updater`ы, заменил на Mapstruct

2024-10-23 23:04 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/category/CategoryService.java
> +    Category getCategoryByName(String name);
В ChannelUpdateDTO передается название категории. В Channel храниться сама категория. Следовательно, мне нужно делать поиск по имени и передавать имя, а не id категории.

2024-10-23 23:05 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementService.java
> +    ChannelExtendedInfoDTO applyPatchToChannel(Long channelId, JsonPatch patch) throws JsonPatchException, JsonProcessingException;
исправил на patchChannel

2024-10-23 23:06 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/channel/management/ChannelManagementServiceImpl.java
> +                new CategoryChannelUpdater(categoryService)
убрал этот бред)

2024-10-23 23:06 UTC, youngliqui commented on src/main/java/ru/clevertec/videohosting_api/service/user/management/UserManagementService.java
> +    User applyPatchToUser(Long userId, JsonPatch patch) throws JsonPatchException, JsonProcessingException;
Изменил на patchUser

2024-12-27 15:49 UTC, merged